version: 0.0
os: linux
files:
  - source: appspec.yml
    destination: /var/www/html/appspec.yml
    overwrite: true
  - source: /build/
    destination: /var/www/html/build/
    overwrite: true
  - source: /scripts/
    destination: /var/www/html/scripts/
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/copy_build_to_html.sh
      timeout: 300
      runas: root
    - location: scripts/restart_apache.sh
      timeout: 300
      runas: root
